local theme = require("user.highlight.theme.tokyonight")
local base16, colors = theme.base_16, theme.base_30

-- nvim cmp
vim.api.nvim_set_hl(0, "CmpItemAbbr", { fg = colors.white })
vim.api.nvim_set_hl(0, "CmpItemAbbrMatch", { fg = colors.blue, bold = true })
vim.api.nvim_set_hl(0, "CmpBorder", { fg = colors.grey })
vim.api.nvim_set_hl(0, "CmpDocBorder", { fg = colors.darker_black, --[[bg = colors.darker_black--]] })
vim.api.nvim_set_hl(0, "CmPmenu", { bg = colors.darker_black })

-- cmp item kinds
vim.api.nvim_set_hl(0, "CmpItemKindhl.Constant", { fg = base16.base09 })
vim.api.nvim_set_hl(0, "CmpItemKindFunction", { fg = base16.base0D })
vim.api.nvim_set_hl(0, "CmpItemKindIdentifier", { fg = base16.base08 })
vim.api.nvim_set_hl(0, "CmpItemKindField", { fg = base16.base08 })
vim.api.nvim_set_hl(0, "CmpItemKindVariable", { fg = base16.base0E })
vim.api.nvim_set_hl(0, "CmpItemKindSnippet", { fg = colors.red })
vim.api.nvim_set_hl(0, "CmpItemKindText", { fg = base16.base0B })
vim.api.nvim_set_hl(0, "CmpItemKindStructure", { fg = base16.base0E })
vim.api.nvim_set_hl(0, "CmpItemKindType", { fg = base16.base0A })
vim.api.nvim_set_hl(0, "CmpItemKindKeyword", { fg = base16.base07 })
vim.api.nvim_set_hl(0, "CmpItemKindMethod", { fg = base16.base0D })
vim.api.nvim_set_hl(0, "CmpItemKindhl.Constructor", { fg = colors.blue })
vim.api.nvim_set_hl(0, "CmpItemKindFolder", { fg = base16.base07 })
vim.api.nvim_set_hl(0, "CmpItemKindModule", { fg = base16.base0A })
vim.api.nvim_set_hl(0, "CmpItemKindProperty", { fg = base16.base08 })
-- vim.api.nvim_set_hl(0, "CmpItemKindEnum", { fg = "" })
vim.api.nvim_set_hl(0, "CmpItemKindUnit", { fg = base16.base0E })
-- vim.api.nvim_set_hl(0, "CmpItemKindhl.Class", { fg = "" })
vim.api.nvim_set_hl(0, "CmpItemKindFile", { fg = base16.base07 })
-- vim.api.nvim_set_hl(0, "CmpItemKindInterface", { fg = "" })
vim.api.nvim_set_hl(0, "CmpItemKindhl.Color", { fg = colors.red })
vim.api.nvim_set_hl(0, "CmpItemKindReference", { fg = base16.base05 })
-- vim.api.nvim_set_hl(0, "CmpItemKindEnumMember", { fg = "" })
vim.api.nvim_set_hl(0, "CmpItemKindStruct", { fg = base16.base0E })
-- vim.api.nvim_set_hl(0, "CmpItemKindValue", { fg = "" })
-- vim.api.nvim_set_hl(0, "CmpItemKindEvent", { fg = "" })
vim.api.nvim_set_hl(0, "CmpItemKindOperator", { fg = base16.base05 })
vim.api.nvim_set_hl(0, "CmpItemKindTypeParameter", { fg = base16.base08 })
vim.api.nvim_set_hl(0, "CmpItemKindhl.Copilot", { fg = colors.green })
